(package "paperless"
         "1.3.1"
         "A major mode for sorting and filing PDF documents")

(website-url "https://github.com/atgreen/paperless")
(keywords "convenience" "pdf")

(package-file "paperless.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "f" "0.11.0")
(depends-on "s" "1.10.0")
(depends-on "cl-lib" "0.7.1")
